server:
  port: 9000 # 端口
spring:
  application:
    name: openpark # 项目名称
  ## 使用阿里druid数据源连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.102:3306/parkdb?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: test
    password: aabbcc2020
    druid:
      initialSize: 5  # 初始建立连接数量
      minIdle: 5  # 最小连接数量
      maxActive: 20 # 最大连接数量
      maxWait: 10000  # 获取连接最大等待时间，毫秒
      testOnBorrow: true # 申请连接时检测连接是否有效
      testOnReturn: false # 归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 # 配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  # 连接在连接池的最小生存时间（毫秒）
  ## jpa配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML5
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    servlet:
      content-type: text/html

## 分页
pagehelper:
  helper-dialect: mysql

## 停车场信息配置
parkInfo:
  ## 是否对接智慧停车
  isEpark: true
  ## 是否对接led和喇叭
  isVoice: true

# 打开调试模式
logging:
  #  level:
  #    com:
  #      lann:
  #        openpark: DEBUG
  config: classpath:logback-spring.xml




